name: build

on: [push]

jobs:
  build:
    name: Build Images and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Buildx (push image)
        run: |
          docker buildx build --push \
          --platform linux/arm/v7,linux/amd64 \
          -t acornforth/train-departure-pi:latest