name: build

on: [push]

jobs:
  build:
    name: build images and push
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx ls
          docker buildx build --platform linux/arm/v7,linux/amd64 -t train-departure .